
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '467B21890FB2BA00899A986AB6968EB6'
    
_lr_action_items = {'MODULE':([0,3,28,],[5,5,-4,]),'$end':([0,1,2,3,4,6,28,],[-33,0,-1,-33,-3,-2,-4,]),'ID':([5,9,11,14,16,18,19,20,21,22,23,25,34,35,37,46,51,58,61,],[7,13,14,27,14,-19,-20,31,-11,-12,-13,13,40,-10,48,56,40,-21,40,]),'LPAREN':([7,27,56,],[9,34,61,]),'SEMI':([7,8,10,30,31,32,36,38,48,49,57,],[-33,11,-6,35,-33,-5,-14,-16,-33,58,-15,]),'ENDMODULE':([11,15,16,17,18,19,29,35,58,],[-33,28,-33,-18,-19,-20,-17,-10,-21,]),'INPUT':([11,16,18,19,35,58,],[21,21,-19,-20,-10,-21,]),'OUTPUT':([11,16,18,19,35,58,],[22,22,-19,-20,-10,-21,]),'WIRE':([11,16,18,19,35,58,],[23,23,-19,-20,-10,-21,]),'COMMA':([12,13,31,33,34,40,42,43,44,45,47,48,51,59,60,65,],[25,-7,37,25,-33,-32,51,54,-24,-25,-31,37,-33,51,54,-28,]),'RPAREN':([12,13,24,26,33,34,39,40,41,42,43,44,45,47,50,51,52,53,55,59,60,62,63,64,65,],[-33,-7,32,-9,-33,-33,-8,-32,49,-33,-33,-24,-25,-31,-22,-33,-27,-23,-30,-33,-33,-26,-29,65,-28,]),'DOT':([34,54,],[46,46,]),'INTEGER':([34,51,61,],[47,47,47,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'source_text':([0,],[1,]),'module_star':([0,3,],[2,6,]),'module':([0,3,],[3,3,]),'empty':([0,3,7,11,12,16,31,33,34,42,43,48,51,59,60,],[4,4,10,17,26,17,38,26,45,52,55,38,45,52,55,]),'list_of_ports':([7,],[8,]),'port':([9,25,],[12,33,]),'module_item_star':([11,16,],[15,29,]),'module_item':([11,16,],[16,16,]),'module_instantiation':([11,16,],[18,18,]),'declaration':([11,16,],[19,19,]),'port_type':([11,16,],[20,20,]),'more_ports':([12,33,],[24,39,]),'list_of_variables':([20,],[30,]),'more_variables':([31,48,],[36,57,]),'list_of_module_connections':([34,],[41,]),'module_port_connection':([34,51,],[42,59,]),'named_port_connection':([34,54,],[43,60,]),'expression':([34,51,61,],[44,44,64,]),'more_module_ports':([42,59,],[50,62,]),'more_named_ports':([43,60,],[53,63,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> source_text","S'",1,None,None,None),
  ('source_text -> module_star','source_text',1,'p_source_text','veriparse.py',19),
  ('module_star -> module module_star','module_star',2,'p_module_star','veriparse.py',23),
  ('module_star -> empty','module_star',1,'p_module_star','veriparse.py',24),
  ('module -> MODULE ID list_of_ports SEMI module_item_star ENDMODULE','module',6,'p_module','veriparse.py',31),
  ('list_of_ports -> LPAREN port more_ports RPAREN','list_of_ports',4,'p_list_of_ports','veriparse.py',35),
  ('list_of_ports -> empty','list_of_ports',1,'p_list_of_ports','veriparse.py',36),
  ('port -> ID','port',1,'p_port','veriparse.py',43),
  ('more_ports -> COMMA port more_ports','more_ports',3,'p_more_ports','veriparse.py',48),
  ('more_ports -> empty','more_ports',1,'p_more_ports','veriparse.py',49),
  ('declaration -> port_type list_of_variables SEMI','declaration',3,'p_declaration','veriparse.py',56),
  ('port_type -> INPUT','port_type',1,'p_port_type','veriparse.py',60),
  ('port_type -> OUTPUT','port_type',1,'p_port_type','veriparse.py',61),
  ('port_type -> WIRE','port_type',1,'p_port_type','veriparse.py',62),
  ('list_of_variables -> ID more_variables','list_of_variables',2,'p_list_of_variables','veriparse.py',66),
  ('more_variables -> COMMA ID more_variables','more_variables',3,'p_more_variables','veriparse.py',70),
  ('more_variables -> empty','more_variables',1,'p_more_variables','veriparse.py',71),
  ('module_item_star -> module_item module_item_star','module_item_star',2,'p_module_item_star','veriparse.py',78),
  ('module_item_star -> empty','module_item_star',1,'p_module_item_star','veriparse.py',79),
  ('module_item -> module_instantiation','module_item',1,'p_module_item','veriparse.py',85),
  ('module_item -> declaration','module_item',1,'p_module_item','veriparse.py',86),
  ('module_instantiation -> ID ID LPAREN list_of_module_connections RPAREN SEMI','module_instantiation',6,'p_module_instantiation','veriparse.py',90),
  ('list_of_module_connections -> module_port_connection more_module_ports','list_of_module_connections',2,'p_list_of_module_connections','veriparse.py',94),
  ('list_of_module_connections -> named_port_connection more_named_ports','list_of_module_connections',2,'p_list_of_module_connections','veriparse.py',95),
  ('module_port_connection -> expression','module_port_connection',1,'p_module_port_connection','veriparse.py',99),
  ('module_port_connection -> empty','module_port_connection',1,'p_module_port_connection','veriparse.py',100),
  ('more_module_ports -> COMMA module_port_connection more_module_ports','more_module_ports',3,'p_more_module_ports','veriparse.py',104),
  ('more_module_ports -> empty','more_module_ports',1,'p_more_module_ports','veriparse.py',105),
  ('named_port_connection -> DOT ID LPAREN expression RPAREN','named_port_connection',5,'p_named_port_connection','veriparse.py',112),
  ('more_named_ports -> COMMA named_port_connection more_named_ports','more_named_ports',3,'p_more_named_ports','veriparse.py',116),
  ('more_named_ports -> empty','more_named_ports',1,'p_more_named_ports','veriparse.py',117),
  ('expression -> INTEGER','expression',1,'p_expression','veriparse.py',125),
  ('expression -> ID','expression',1,'p_expression','veriparse.py',126),
  ('empty -> <empty>','empty',0,'p_empty','veriparse.py',130),
]
